language: node_js
node_js:
  - "stable"
dist: trusty
addons:
  apt:
    packages:
      - libnss3
sudo: required
notifications:
  email: false
cache:
  directories:
    - node_modules
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
  # Launch XVFB
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - npm run ci
